---

- name: Managing files
  file:
    path:   "{{ item.path }}"
    follow: "{{ item.follow | default(omit) }}"
    force:  "{{ item.force  | default(omit) }}"
    group:  "{{ item.group  | default(omit) }}"
    mode:   "{{ item.mode   | default(omit) }}"
    owner:  "{{ item.owner  | default(omit) }}"
    src:    "{{ item.src    | default(omit) }}"
    state:  "{{ item.state  | default(omit) }}"
  with_flattened:
    - files
    - files_group_list
    - files_host_list
